
project_id = "catchattack-platform"

[api]
port = 54321
schemas = ["public", "storage"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
port = 54323

[auth]
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
enable_signup = true

[inbucket]
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
file_size_limit = "50MiB"

[functions]
serve_port = 54327

[functions.ai-rule-generation]
verify_jwt = true

[functions.ai-anomaly-detection]
verify_jwt = true

[functions.ai-mitre-techniques]
verify_jwt = true

[functions.ai-predictive-scheduling]
verify_jwt = true

[functions.ai-rule-similarity]
verify_jwt = true

[functions.ai-status]
verify_jwt = true

[functions.caldera-integration]
verify_jwt = true

[functions.vm-generator]
verify_jwt = true

[minio]
port = 54328
console_port = 54329
