[mypy]
python_version = 3.12
strict = True
warn_unused_configs = True
warn_redundant_casts = True
warn_unused_ignores = True
warn_return_any = True
disallow_untyped_defs = True
disallow_incomplete_defs = True
no_implicit_optional = True
check_untyped_defs = True
exclude = (^legacy/|^\.venv/)

[mypy-tests.*]
disallow_untyped_defs = False
