version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: catchattack
    ports: ["5432:5432"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile.api
    environment:
      ENV: dev
      DB_DSN: postgresql+psycopg://postgres:postgres@db:5432/catchattack
      CORS_ORIGINS: http://localhost:3000
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel:4318
    depends_on:
      db:
        condition: service_healthy
    ports: ["8000:8000"]

  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile.web
    environment:
      VITE_API_BASE: http://localhost:8000
    depends_on:
      - api
    ports: ["3000:80"]

  elastic:
    build:
      context: ..
      dockerfile: docker/Dockerfile.elastic
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports: ["9200:9200"]

  otel:
    image: otel/opentelemetry-collector:0.103.1
    command: ["--config=/etc/otel-config.yaml"]
    volumes:
      - ./docker/otel-config.yaml:/etc/otel-config.yaml:ro
    ports: ["4318:4318"]
