---
receivers:
  otlp:
    protocols:
      http:

exporters:
  logging:
    loglevel: info

processors:
  batch: {}

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging]
