// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tfidqcgdzclihkwquwfn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRmaWRxY2dkemNsaWhrd3F1d2ZuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1OTE1ODYsImV4cCI6MjA2MDE2NzU4Nn0.Ps-1_MtfhAOOf5YNjEMkSVdx7-weTKvV3d-yFoics7s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);