---
name: backend

'on':
  push:
    paths:
      - 'backend/**'
      - 'tests/**'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - run: pip install -r backend/requirements.txt pytest pytest-cov ruff mypy
      - run: |
          ruff check backend
          mypy backend || true
      - run: docker compose -f docker/docker-compose.yml up -d db api otel
      - run: |
          for i in {1..30}; do
            if curl -sSf http://localhost:8000/api/v1/healthz >/dev/null; then
              break
            fi
            sleep 2
          done
      - run: PYTHONPATH=backend pytest -c backend/pytest.ini
      - run: docker compose -f docker/docker-compose.yml down
        if: always()
